from __future__ import annotations

MAX_WORKERS = 3
DELAY_BETWEEN_REQUESTS = 2.5
REQUEST_JITTER_SECONDS = 0.6
TIMEOUT_SECONDS = 20
CONNECT_TIMEOUT_SECONDS = 8
READ_TIMEOUT_SECONDS = 20
MAX_RETRIES = 3
RETRY_BASE_DELAY_SECONDS = 2.0
RETRY_BACKOFF_FACTOR = 2.0
RETRY_MAX_DELAY_SECONDS = 20.0
RETRYABLE_STATUS_CODES = {408, 425, 429, 500, 502, 503, 504}
OUTPUT_FILENAME = "seo_audit_report.xlsx"
DEFAULT_OWNER_BY_SEVERITY = {"Critical": "Dev", "Warning": "Copy Writer", "Info": "Copy Writer"}
DEFAULT_EFFORT_BY_SEVERITY = {"Critical": "M", "Warning": "S", "Info": "S"}
